# should be kep outside policies becuase modification to experiments changes the ultra-score
observation_num_lookahead: 20
social_vehicles:
    encoder_key: precog_encoder
    social_policy_hidden_units: 128
    social_policy_init_std: 0.5
    social_capacity: 10
    num_social_features: 4
    seed: 2
